//
//  nicknames.swift
//  FuzzyNames
//
//  Created by Andrew Zamler-Carhart on 3/5/20.
//  Copyright © 2020 Andrew Zamler-Carhart. All rights reserved.
//

import Foundation

let punctuation = [".", ",", "(", ")", "|"]
let substitutions = ["-":" ", "ł":"l"]
let suffixes = ["Esq", "JD", "MBA", "PA", "PhD", "Jr","II", "III"].map { " " + $0.lowercased() }

let nicknames = [
    ["abigail", "abbey", "abby"],
    ["albert", "al"],
    ["alex", "alejandro", "alexander", "alexandar", "alexandra", "ali", "sasha"],
    ["alison", "allison", "ali", "allie", "ally"],
    ["amanda", "mandy"],
    ["ana", "annie"],
    ["andrew", "andy", "drew"],
    ["anthony", "tony"],
    ["arthur", "art", "arty"],
    ["bartholomew", "bartlomiej", "bart"],
    ["benjamin", "ben"],
    ["bernard", "bernie", "bern"],
    ["bradley", "brad"],
    ["caroline", "carolyn"],
    ["cassie", "catherine"],
    ["cat", "catherine", "cathie"],
    ["cait", "catherine", "cathy", "ekaterina", "kait", "kaitlin", "kat", "kate", "katelyn", "katerina", "katharine", "katherine", "katheryn", "kathleen", "kathryn", "kathy", "katie", "katrina", "katy", "yekaterina"],
    ["charles", "charlie", "chuck"],
    ["christopher", "christina", "christine", "chris", "chrissy", "chrissie", "tina"],
    ["cindi", "cynthia", "cindee"],
    ["cynthia", "cindy", "cynth"],
    ["daniel", "dan", "danny", "dani", "danielle"],
    ["david", "dave"],
    ["deb", "debra", "debbi", "debbie", "deborah", "debbie"],
    ["dennis", "denny"],
    ["donald", "don", "donnie", "donny"],
    ["dyanne", "dee dee"],
    ["edward", "ed", "eddie", "ted", "eduardo"],
    ["elena", "yelena"],
    ["eli", "eliezer", "elias"],
    ["elizabeth", "betty", "beth", "liz", "lizzy", "lizzie", "lisbeth", "lizbeth", "lisa", "lizz"],
    ["eugene", "gene"],
    ["florence", "flo"],
    ["frances", "fran", "francie", "francis", "frank"],
    ["frederick", "fred", "freddy"],
    ["gabby", "gabriela", "gabi", "gabrielle", "gaby"],
    ["giannina", "gina"],
    ["gregory", "greg"],
    ["henry", "hank"],
    ["irving", "irv"],
    ["jacci", "jacqueline", "jacki", "jackie", "jaclyn"],
    ["jake", "jacob"],
    ["james", "jim", "jimmy"],
    ["janet", "janice", "jan"],
    ["jed", "jedediah", "jebediah"],
    ["jeffrey", "jeff"],
    ["jennifer", "jenny", "jenn", "jen"],
    ["joanie", "joan"],
    ["joey", "joel"],
    ["john", "jonathan", "jonny", "johnny", "jony", "jack", "jon"],
    ["joseph", "joe"],
    ["joshua", "josh"],
    ["judith", "judy", "judi"],
    ["kenneth", "ken", "kenny"],
    ["kimberley", "kimberly", "kim"],
    ["lawrence", "larry"],
    ["laura", "lauren", "laurie", "laurine", "laurene"],
    ["leonard", "leo"],
    ["lily", "lil", "lillian", "lili", "liliana", "lilly", "lillian"],
    ["margaret", "maggie", "margy", "margie", "meg", "megan"],
    ["maria", "masha"],
    ["matthew", "matt"],
    ["michael", "mike"],
    ["nancy", "nan"],
    ["nathan", "nat", "nate"],
    ["nicholas", "nick"],
    ["norman", "norm"],
    ["pamela", "pam"],
    ["patrick", "patricia", "patrice", "patty", "pat", "patti"],
    ["peter", "pete"],
    ["philip", "phillip", "phil"],
    ["rammy", "ram"],
    ["raymond", "ray"],
    ["renée", "renee"],
    ["richard", "dick", "rick", "rich"],
    ["robert", "bob", "bobby", "rob", "roberta", "bobbie", "robby", "robbie"],
    ["rodrigo", "rod"],
    ["ronald", "ron", "ronny", "ronnie", "veronica"],
    ["russell", "russ"],
    ["samuel", "sam", "sammy", "sammie", "samantha"],
    ["sophia", "sophie"],
    ["stephen", "steven", "steve"],
    ["stuart", "stu"],
    ["susan", "sue", "suzie"],
    ["svetlana", "sveta", "lana"],
    ["tammy", "tamara", "tammie", "tamala"],
    ["teresa", "terry", "terrence", "teri", "theresa", "therese"],
    ["theodore", "theo", "ted", "teddy"],
    ["thomas", "tom", "thom", "tommy", "tommie"],
    ["timothy", "tim", "timmy", "timmie"],
    ["toby", "tobin"],
    ["tori", "victoria", "tory", "vickie", "vicky"],
    ["tracy", "traci"],
    ["trisha", "patricia", "trish"],
    ["valerie", "val"],
    ["vincent", "vince"],
    ["walter", "walt", "wally"],
    ["william", "will", "willy", "bill", "billy"], // or mack or buddy
    ["wolf", "wolfgang"],
    ["yianni", "ioannis"],
    ["zachary", "zac", "zach", "zack"]
]

